using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Contains helpful data and methods for manipulating keycodes.
/// </summary>
public static class KeyCodeExtensions
{
    public static Dictionary<KeyCode, string> keyCodeNames = new Dictionary<KeyCode, string>()
    {
        { KeyCode.Mouse0, "Left Click" },
        { KeyCode.Mouse1, "Right Click" },
        { KeyCode.None, "None" },
        { KeyCode.Backspace, "Backspace" },
        { KeyCode.Delete, "Delete" },
        { KeyCode.Tab, "Tab" },
        { KeyCode.Clear, "Clear" },
        { KeyCode.Return, "Enter" },
        { KeyCode.Pause, "Pause" },
        { KeyCode.Escape, "Escape" },
        { KeyCode.Space, "Spacebar" },
        { KeyCode.Keypad0, "[0]" },
        { KeyCode.Keypad1, "[1]" },
        { KeyCode.Keypad2, "[2]" },
        { KeyCode.Keypad3, "[3]" },
        { KeyCode.Keypad4, "[4]" },
        { KeyCode.Keypad5, "[5]" },
        { KeyCode.Keypad6, "[6]" },
        { KeyCode.Keypad7, "[7]" },
        { KeyCode.Keypad8, "[8]" },
        { KeyCode.Keypad9, "[1]" },
        { KeyCode.KeypadPeriod, "[.]" },
        { KeyCode.KeypadDivide, "[/]" },
        { KeyCode.KeypadMultiply, "[*]" },
        { KeyCode.KeypadMinus, "[-]" },
        { KeyCode.KeypadPlus, "[+]" },
        { KeyCode.KeypadEnter, "[Enter]" },
        { KeyCode.KeypadEquals, "[=]" },
        { KeyCode.UpArrow, "Up Arrow" },
        { KeyCode.DownArrow, "Down Arrow" },
        { KeyCode.RightArrow, "Right Arrow" },
        { KeyCode.LeftArrow, "Left Arrow" },
        { KeyCode.Insert, "Insert" },
        { KeyCode.Home, "Home" },
        { KeyCode.End, "End" },
        { KeyCode.PageUp, "Page Up" },
        { KeyCode.PageDown, "Page Down" },
        { KeyCode.F1, "F1" },
        { KeyCode.F2, "F2" },
        { KeyCode.F3, "F3" },
        { KeyCode.F4, "F4" },
        { KeyCode.F5, "F5" },
        { KeyCode.F6, "F6" },
        { KeyCode.F7, "F7" },
        { KeyCode.F8, "F8" },
        { KeyCode.F9, "F9" },
        { KeyCode.F10, "F10" },
        { KeyCode.F11, "F11" },
        { KeyCode.F12, "F12" },
        { KeyCode.Alpha0, "0" },
        { KeyCode.Alpha1, "1" },
        { KeyCode.Alpha2, "2" },
        { KeyCode.Alpha3, "3" },
        { KeyCode.Alpha4, "4" },
        { KeyCode.Alpha5, "5" },
        { KeyCode.Alpha6, "6" },
        { KeyCode.Alpha7, "7" },
        { KeyCode.Alpha8, "8" },
        { KeyCode.Alpha9, "9" },
        { KeyCode.Quote, "Quote" },
        { KeyCode.Comma, "Comma" },
        { KeyCode.Minus, "Minus" },
        { KeyCode.Period, "Period" },
        { KeyCode.Slash, "Slash" },
        { KeyCode.Semicolon, "Semicolon" },
        { KeyCode.Equals, "Equals" },
        { KeyCode.LeftBracket, "Left Bracket" },
        { KeyCode.Backslash, "Backslash" },
        { KeyCode.RightBracket, "Right Bracket" },
        { KeyCode.BackQuote, "Back Quote" },
        { KeyCode.RightShift, "Right Shift" },
        { KeyCode.LeftShift, "Shift" },
        { KeyCode.RightControl, "Right Control" },
        { KeyCode.LeftControl, "Control" },
        { KeyCode.RightAlt, "Right Alt" },
        { KeyCode.LeftAlt, "Alt" }
    };
}
